[package]
name = "RustRocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = {version = "0.5.0-rc.2", features = ["json"]}
rocket_contrib = "0.4.10"
serde = "1.0.136"
dotenv = "0.15.0"
