# Generated by Django 4.1.7 on 2023-02-22 04:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'todo_lists',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TodoUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=31, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('user_password', models.CharField(max_length=31, validators=[django.core.validators.RegexValidator("(?=^.{6,31}$)(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&amp;*()_+}{&quot;:;'?/&gt;.&lt;,])(?!.*\\s).*$")])),
                ('user_email', models.CharField(max_length=31, unique=True, validators=[django.core.validators.EmailValidator()])),
            ],
            options={
                'db_table': 'todo_users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todolists')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todousers')),
            ],
            options={
                'db_table': 'todos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='todolists',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.todousers'),
        ),
    ]
